apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector: # filter pods of a deployment based on labels
    app: goserver
  type: ClusterIP
  ports:
    - name: goserver-service
      protocol: TCP
      port: 8080 # service port
      targetPort: 8000 # container port
